platform:ios, ‘8.0’

source 'https://github.com/CocoaPods/Specs.git'

target “LightMapDemo” do

pod 'BaiduMapKit', '~> 3.3.0'
pod “MJExtension”,”~> 3.0.10”
pod “SVProgressHUD”,”~> 1.1.3”
pod 'Aspects', '~> 1.4.1'
end
